name: 'Docker container action to Lint OpenAPI doc'
description: 'JSON/YAML linter with out of the box support for OpenAPI 3.x and 2.0'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  file_path:
    description: 'Path to OpenAPI file for validation'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file_path }}
